name: Deploy

on:
  workflow_call:
    inputs:
      publish:
        description: 'Flag to trigger publish'
        required: true
        type: boolean
      production:
        description: 'Whether push to production or not.'
        required: true
        type: boolean


jobs:
  tests:
    permissions:
      contents: read

    uses: ./.github/workflows/_tests.yml

  publish:
    needs: [tests]
    if: ${{ inputs.publish }}

    uses: ./.github/workflows/_publish.yml
    with:
      production: ${{ inputs.production }}
    secrets: inherit
