name: Deploy

on:
  workflow_call:
    inputs:
      publish:
        description: 'Flag to trigger publish'
        required: true
        type: boolean
      branch:
        description: 'Branch name'
        required: true
        type: string


jobs:
  tests:
    permissions:
      contents: read

    uses: ./.github/workflows/_tests.yml

  publish:
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ inputs.publish == true }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/_publish.yml
        with:
          production: ${{ inputs.branch == 'main' }}
