name: Publish

on:
  workflow_call:
    inputs:
      production:
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v2

      - name: Install Dependencies
        run: |
          uv sync --no-dev

      - name: Build Package
        run: uv build

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 1

  test-pypi:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ !inputs.production }}

    steps:
      - uses: actions/checkout@v4

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: dist 
          path: dist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          username: __token__
        env:
          TWINE_DISABLE_OIDC: '1'

  prod-pypi:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ inputs.production }}

    steps:
      - uses: actions/checkout@v4

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Publish
        run: |
          uv publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
