name: Rollback

on: workflow_call

jobs:
  revert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
          
      - name: Set Up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
    
      - name: Revert Last Commit
        run: |
          git revert --no-edit HEAD
          git push
