name: Develop Branch

on:
    push:
        branches:
        - develop
    pull_request:
        branches:
        - develop

jobs:
    deploy:
        uses: ./.github/workflows/_deploy.yml
        with:
            publish: false
            production: false
        secrets: inherit
