name: Develop Branch

on:
    push:
        tags:
        - 'v*'
        branches:
        - develop
    pull_request:
        branches:
        - develop

jobs:
    deploy:
        uses: ./.github/workflows/_deploy.yml
        with:
            publish: ${{ startsWith(github.ref, 'refs/tags/v') }}
            branch: 'develop'
