name: Main Branch

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    deploy:
        uses: ./.github/workflows/_deploy.yml
        with:
            publish: true
            production: false
        secrets: inherit
