name: Publish Package

on:
  workflow_run:
    workflows: [Run Tests]
    types: [completed]
    branches:
      - develop

permissions:
  contents: read

jobs:
  build-package:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v4

    - name: install uv
      uses: astral-sh/setup-uv@v2

    - name: install dependencies
      run: |
        uv sync --no-dev

    - name: build package
      run: uv build

  test-pypi:
    name: Publish to test pypi
    runs-on: ubuntu-latest
    needs: [build-package]
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}

    permissions:
      id-token: write 

    steps:
      - uses: actions/checkout@v4

      - name: publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
  